name: pure_dart_extensions
description: Set of method-extensions for pure dart that makes using framework in a much easier and clean way also adds additional functionality.
version: 3.0.1
documentation: https://github.com/wilinz/pure_dart_extentions
homepage: https://github.com/wilinz/pure_dart_extentions

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  quiver: ^3.2.1
  http: ^1.1.0

dev_dependencies:
  test: ^1.25.15

index_generator:
  exclude:
    - '**.g.dart'
  # Define the paths of the folders in which to generate the index files
  libraries:
    - directory_path: lib